# Generated by Django 4.0.6 on 2022-07-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('type', models.CharField(max_length=8)),
                ('restLogger', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('IP', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('requestType', models.CharField(max_length=4)),
                ('params', models.CharField(max_length=64)),
                ('URL', models.CharField(max_length=256)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.log')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.timeline'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('statusCode', models.IntegerField()),
                ('hostname', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=45)),
                ('result', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=64)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.log')),
            ],
        ),
    ]
