# Generated by Django 4.0.6 on 2022-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('SENT', 'SENT'), ('RECIEVED', 'RECIEVED')], max_length=8),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=4),
        ),
    ]
