# Generated by Django 4.0.6 on 2022-08-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_log_type_alter_request_requesttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeline',
            name='IP',
            field=models.CharField(max_length=45),
        ),
    ]
