# Generated by Django 4.0.6 on 2022-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_timeline_id_alter_timeline_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='ID',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='IP',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
